### ISSUE TITLE
Invalid or unknown key. Examine values at 'ServiceVcl.LoggingKineses'

### ISSUE THREAD

**Issue by Ira-Varganovska** [pulumi/pulumi-fastly#159]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm getting error `Invalid or unknown key. Examine values at 'ServiceVcl.LoggingKineses'` when trying to add logging to Kineses.
The issue is reproduced on all versions 2.15.0, 3.X, 4.0.0.
The issue appears if `loggingKineses` is added to `ServiceVclArgs` (`Servicev1Args`)
Similar behavior is observed for `loggingHerokus`. All other types of logging args have no such issue.

### Steps to reproduce

1. Create the service with argument `loggingKineses: []`
2. Run `pulumi preview`

#### Example
```
import * as fastly from "@pulumi/fastly";

const service = new fastly.ServiceVcl("my-service", {
  loggingKineses: [],
  backends: [{
       address: "127.0.0.1",
       name: "localhost",
       port: 80
   }],
  domains: [{
       comment: "demo",
       name: "demo.pulumi.com",
  }],
  forceDestroy: true,
});
```

Expected: No error is returned
Actual:  has a problem: Invalid or unknown key. Examine values at 'ServiceVcl.LoggingKineses'.

**Comment by rexoafastly** [comment]
Hi All. I am by no means a Pulumi expert but could this perhaps be a typo? The reference to Amazon [Kinesis](https://aws.amazon.com/kinesis/?trk=56601b48-df3f-4cb4-9ef7-9f52efa1d0b8&sc_channel=ps&sc_campaign=acquisition&sc_medium=ACQ-P%7CPS-GO%7CNon-Brand%7CDesktop%7CSU%7CAnalytics%7CSolution%7CUS%7CEN%7CDSA&ef_id=Cj0KCQjw29CRBhCUARIsAOboZbLgPSU_x6yx87wmgVjBSfdSujwp85YO0q1NZSoDuLdjpPkEbALbQQEaAlGqEALw_wcB:G:s&s_kwcid=AL!4422!3!579408011996!!!g!!) key in the example seems to be mis-spelled as `loggingKineses`, with an `e` instead of `i`. Thoughts?

**Comment by jkodroff** [comment]
@rexoafastly I would agree that it's a pluralization mistake (but the name actually is `loggingKineses` in the generated code. I think this weirdness is an issue with our pluralization where it thinks it's a Latin term, e.g. "thesis" -> "theses". Could you file a separate issue for this?

**Comment by Harry-027** [comment]
I'm also facing same issue ! Is it going to be resolved anytime soon ?

**Comment by mjeffryes** [comment]
Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still encountering this problem, could you leave a quick comment to let us know so we can prioritize it? (Commenting will bump it back into our triage queue.)
